### PR TITLE
HddManager: disable the expand option, since it causes corruption

### PR DESCRIPTION
**Pull request by uyjulian**
## Pull Request checklist

Note: these are not necessarily requirements

- [x] I reformatted the code with clang-format
- [x] I checked to make sure my submission worked
- [x] I am the author of submission or have permission from the original author
- [ ] Requires update of the PS2SDK or other dependencies
- [ ] Others (please specify below)

## Pull Request description

Disable the expand option; it doesn't work correctly and may cause corruption.  
I believe this was already done in kHn LE fork.

### CODE REVIEW

**Comment by israpps** [comment]
@uyjulian since you mentioned krHACKen fork...

Could you check the changes he made to allow deletion and renaming of `__` prefixed partitions?

there are some checks that negate this on ATAD itself...

Maybe remove those checks? or restrict them to `__mbr` solely?

**Comment by uyjulian** [comment]
> @uyjulian since you mentioned krHACKen fork...
> 
> Could you check the changes he made to allow deletion and renaming of `__` prefixed partitions?
> 
> there are some checks that negate this on ATAD itself...
> 
> Maybe remove those checks? or restrict them to `__mbr` solely?

Not in the scope of this PR

**Comment by sp193** [comment]
Since the issue is not with LaunchELF itself, why not attempt to fix the logic in the PFS driver or APA driver? Is that not possible?

**Comment by AKuHAK** [comment]
Lgtm

**Comment by israpps** [comment]
> > @uyjulian since you mentioned krHACKen fork...
> > Could you check the changes he made to allow deletion and renaming of `__` prefixed partitions?
> > there are some checks that negate this on ATAD itself...
> > Maybe remove those checks? or restrict them to `__mbr` solely?
> 
> Not in the scope of this PR

I know, just telling you...

Maybe you can check it some day

If you do it before I find the place where the check is placed ofc🤣

**Pull request merged**
