### PR TITLE
Lang: Bringing the 'T' back into Formatted (HddManager)

### PR DESCRIPTION
**Pull request by RedDevilus**
## Pull Request checklist

Note: these are not necessarily requirements

- [x] I reformatted the code with clang-format
- [x] I checked to make sure my submission worked
- [x] I am the author of submission or have permission from the original author
- [ ] Requires update of the PS2SDK or other dependencies
- [ ] Others (please specify below)

## Pull Request description
English consistency for the HddManager (and other locations) as they were typos.

### CODE REVIEW

**Comment by RedDevilus** [comment]
Old:
image

New:
Too lazy to do it.

**Comment by RedDevilus** [comment]
Should've formatted it oops.

image

**Comment by AKuHAK** [comment]
Doh, tgis will break all language files. Can you just fix how its shown in the gui, nit the option name itaelf?

**Comment by RedDevilus** [comment]
I guess it's fine now as it's only the root language (being English), I did read the comments where it generates the language files, but I don't see any mention of like Crowdin or languages in the root which I understand why you don't want the variables changed.

**Comment by RedDevilus** [comment]
image

**Comment by RedDevilus** [comment]
You can merge it now, I tested it and it doesn't touch config files even with other languages.

**Pull request merged**
